server:
  port: 8888
  
spring:
  application:
    name: ms-admin-config-server
    
#Configuracion Local
  profiles:
    active: native
    
  cloud:
    config:
      server:
        native:
          search-locations: ///F:\Desarrollo de Software\5 Quinto Ciclo\Y60\DSBS-Y60\ms-gestion-config-data
      
 
      
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/OliverYR03/Group-02-Microservice.git
#          search-paths: /ms-gestion-config-data/
#          username: ${USER_NAME}
#          password: ${PASSWORD}
#          default-label: main
#          clone-on-start: true
#          ignore-local-ssh-settings: true